### ISSUE TITLE
[PE-D][Tester C] Typo in Start Guide regarding name of jar file to run

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-W13-1/tp#120]
![ugbug1.PNG](https://raw.githubusercontent.com/jeromeongithub/ped/main/files/e46c5f4b-c495-4267-9a58-6494b85b63a8.PNG)

The JAR file to be downloaded and run is actually DrDuke.jar instead of Tp.main.jar.

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: jeromeongithub/ped#1

**Comment by tanyizhe** [comment]
Fixed typo.
