### ISSUE TITLE
[PE-D][Tester B] No way for user to reset password

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-W13-1/tp#122]
If the same username is registered with a different password, it is treated as a different account. This is good for security reasons but it means if a user forgets his password, there is no way to recover their data. A "forgot password" feature should be implemented, with the user required to input their username to be allowed to change it (meaning 2 accounts cannot have the same username, for security).

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: jared-ee/ped#1

**Comment by tanyizhe** [comment]
Not in our scope
