### ISSUE TITLE
[PE-D][Tester A] Outcome different from UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-W13-1/tp#127]
When reporting symptoms, it shows these message.
![Screenshot 2023-03-31 at 4.58.27 PM.png](https://raw.githubusercontent.com/MichelleLiang0116/ped/main/files/1287b782-14e7-48a2-8401-5baf4398c047.png)

![Screenshot 2023-03-31 at 4.58.48 PM.png](https://raw.githubusercontent.com/MichelleLiang0116/ped/main/files/e9c2d53a-86e0-4cf0-b39f-099997b2c9f5.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: MichelleLiang0116/ped#2

**Comment by tanyizhe** [comment]
collated all logging related problems to issue #168
