### ISSUE TITLE
[PE-D][Tester E] DrDuke should not accept when a patient has zero symptoms

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-W13-1/tp#129]
with no entered symptoms, diagnosis is nothing. Hence, DrDuke should give some feedback saying no diagnosis instead of trying to give a diagnosis.
 
![image.png](https://raw.githubusercontent.com/typingpanda/ped/main/files/9481ba9e-a095-4ed8-bd94-7fae3f6ccc87.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: typingpanda/ped#2

**Comment by Jeraldchen** [comment]
Thank you for your feedback we will update this in v2.1!

**Comment by Geeeetyx** [comment]
Done
