### ISSUE TITLE
[PE-D][Tester C] Typo in User Guide regarding what happens after registration and/or logging in

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-W13-1/tp#137]
![image.png](https://raw.githubusercontent.com/jeromeongithub/ped/main/files/6dac84bd-17c6-4d2a-8abb-e2044dfff297.png)

![image.png](https://raw.githubusercontent.com/jeromeongithub/ped/main/files/92e229ab-b6b5-48ad-9b44-25be9ffe841c.png)

After registration, the menu with 9 options does not appear (it only appears after logging in). Perhaps the team meant that the menu with 9 options only appears after logging in?

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: jeromeongithub/ped#5

**Comment by tanyizhe** [comment]
Fixed
