### ISSUE TITLE
[PE-D][Tester D] Unable to use password of choice. 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-W13-1/tp#139]
![image.png](https://raw.githubusercontent.com/nigelhao/ped/main/files/05c63cb9-dd47-454e-b92d-f2403c2a31bc.png)

Above user 1 uses password "ABC" when user 2 tries to use the same password, but it is already in use. 

All users should be able to use password of their choice. 

Anyway, under TP constraint product should be for a single user. 

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: nigelhao/ped#2

**Comment by Thunderdragon221** [comment]
Thanks for the feedback! Do note the following: In account registration, users are typically not allowed to use existing usernames. In our case, we allow users to use any usernames they want, including existing usernames, but of course that also means rejecting use of existing passwords. Unfortunately, its a tradeoff that needs to be made.
