### ISSUE TITLE
[PE-D][Tester D] View Symptoms History text not friendly

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-W13-1/tp#145]
![image.png](https://raw.githubusercontent.com/nigelhao/ped/main/files/6d867269-7bdc-421a-86c9-5e64535794b4.png)

Text is not user friendly. Using all caps and snake_case.

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: nigelhao/ped#5

**Comment by Jeraldchen** [comment]
Thank you for your feedback we will be updating this in v2.1
