### ISSUE TITLE
[PE-D][Tester D] What if possible symptoms grows?

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-W13-1/tp#154]
![image.png](https://raw.githubusercontent.com/nigelhao/ped/main/files/1c6d8717-8f19-4050-a177-bb97ee8ebbd7.png)

Suppose the static possible symptoms grows. How will the user select the possible inputs? "aa" "ab" "a1"? These wouldn't work, because "aaa" will consider as 3 different "a" inputs

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: nigelhao/ped#9

**Comment by tanyizhe** [comment]
@Brennanzuz I think you have a "severity" measure right? is it possible to let user control that variable? if not we could just close it because it's not in our scope

**Comment by Jeraldchen** [comment]
Our application only caters to mild illnesses and symptoms. We do not aim to replace professional Doctors and as such, we would consider including a feature where we would direct the patient to consult a doctor should their symptom not be identified by our application,

**Comment by Brennanzuz** [comment]
> @Brennanzuz I think you have a "severity" measure right? is it possible to let user control that variable? if not we could just close it because it's not in our scope

The severity measure was a constant value assigned to each value intended to be used for filtering patients that require medical attention from doctors, but has not been put to use yet.

> ![image.png](https://raw.githubusercontent.com/nigelhao/ped/main/files/1c6d8717-8f19-4050-a177-bb97ee8ebbd7.png)
> 
> Suppose the static possible symptoms grows. How will the user select the possible inputs? "aa" "ab" "a1"? These wouldn't work, because "aaa" will consider as 3 different "a" inputs
> 
> Labels: `type.FunctionalityBug` `severity.Low` original: [nigelhao/ped#9](https://github.com/nigelhao/ped/issues/9)

You make a valid point. There are only so few unique characters that a keyboard can input, and only 26+26+10=62 are intuitive for users to input. However, the scope of our project is small enough to not exceed 62 possible symptoms to report and thus this method of inputting is feasible albeit unsustainable in the future.
