### ISSUE TITLE
[PE-D][Tester D] Unable to read which line to edit. 

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-W13-1/tp#155]
![image.png](https://raw.githubusercontent.com/nigelhao/ped/main/files/ba6709ed-a66b-4896-9239-e13707fe9b75.png)

I don't know which line to edit. Thus i will say that it is difficult to read. 

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: nigelhao/ped#10

**Comment by tanyizhe** [comment]
This is not a functionality bug, it is not meant to be read nor edited by a person. The behaviour of the application does not change because of not being readable by humans.
