### ISSUE TITLE
[PE-D][Tester D] Incorrect JAR file name in UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-W13-1/tp#157]
![image.png](https://raw.githubusercontent.com/nigelhao/ped/main/files/e51408c1-f16b-4da8-b422-8a3d3b5b9285.png)

jar file name should be DrDuke.jar

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: nigelhao/ped#12

**Comment by tanyizhe** [comment]
Fixed typo.
