### ISSUE TITLE
NullPointerException when no medication exists for new illness

### ISSUE THREAD

**Issue by Brennanzuz** [AY2223S2-CS2113-W13-1/tp#74]
When adding new symptoms for users to enter in the UI, new illnesses are diagnosed and thus the ArrayList of IllnessMatch contain new illnesses. Medicine may not be assigned to these illnesses and the patient side of things may throw an error. For example, updatePatientMedicineHistory() of Patient.java will cause the program to crash with a NullPointerException as the medicines ArrayList is empty.

I have hence added a makeshift fix with a try catch statement to allow the program to continue. However, there will probably be other unintended consequences when adding new illnesses. Please help to handle such exceptions, thanks! 😄

**Comment by tanyizhe** [comment]
fixed
